### ISSUE TITLE
Can't add Youtube RSS feed

### ISSUE THREAD

**Issue by czarkoff** [CarolusMagnus/Podcatcher#1]
Adding Youtube RSS feeds by URL ([eg.](https://www.youtube.com/feeds/videos.xml?channel_id=UC-yewGHQbNFpDrGM0diZOLA)) leads to "_Fetching channel information_" popup, which just sits there until dismissed.  The feed is never added.

In systemd logs the event shows up with error message "_Provided podcast channel URL is not valid._"

Applies to 1.1 as released to Jolla Store.

**Comment by CarolusMagnus** [comment]
I will investigate this issue if I will have time.

**Comment by CarolusMagnus** [comment]
The problem with the URL was easy to fix, but the structure of the Youtube feeds differs from ordinary podcast feeds. This means a new parser has to be written for this kind of feeds..
