### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by fravaccaro** [CarolusMagnus/Podcatcher#12]
I translated the UI in Italian, unluckily github doesn't support upload of .ts files, so please rename the attaached file.
[harbour-podcatcher-it.ts.txt](https://github.com/CarolusMagnus/Podcatcher/files/453513/harbour-podcatcher-it.ts.txt)

**Comment by CarolusMagnus** [comment]
Thank you very much! I merged your translations.

**Comment by CarolusMagnus** [comment]
I found other strings, which were not yet prepared for translation. Maybe you want to do the Italian localization for them.

**Comment by fravaccaro** [comment]
Sure! Here they are :)

[harbour-podcatcher-it.ts.txt](https://github.com/CarolusMagnus/Podcatcher/files/454026/harbour-podcatcher-it.ts.txt)

**Comment by CarolusMagnus** [comment]
Thank you very much!
