### ISSUE TITLE
Possible db issue

### ISSUE THREAD

**Issue by marxistvegan** [CarolusMagnus/Podcatcher#20]
Starting on or about December 16th the feeds all throw an error on refresh. 
`Podcast feed invalid: cannot download episodes`
this happens with every feed, all of which worked without a problem prior.

**Comment by CarolusMagnus** [comment]
Could you please give an example for a failing feed? I assume there was some update/change  for the software, that creates the feeds.

**Comment by marxistvegan** [comment]
So I had a hard time pulling up an error that gave me any specifics. But they were npr.org podcasts, i was only able to resolve by removing and readding them. I am going to close this cause there is little I can do to get the logs that would be helpful. Thanks for the response though :) happy new year!
