### ISSUE TITLE
[Feature request] Password secured Podcasts

### ISSUE THREAD

**Issue by dasDirksche** [CarolusMagnus/Podcatcher#29]
I would like to download zeit audio podcast episodes. But to do that I have to transmit my credentials. I couldn't find a way to so

**Comment by dasDirksche** [comment]
Hi,

yes I did try to give the credentials in the url. But unfortunatly it does not work.

I tried: https://dirksche:mypassword@premium.zeit.de/audio/podcast

See the picture

Greetings

Am Freitag, 5. Januar 2018 schrieb CarolusMagnus:

**Comment by CarolusMagnus** [comment]
I can't see any picture. If I have some time, I will register for the free trial and try to understand and implement the sign in process.

**Comment by dasDirksche** [comment]
Thanks a lot

Am Freitag, 5. Januar 2018 schrieb CarolusMagnus:

**Comment by CarolusMagnus** [comment]
I haven't registered for Zeit Audio, but updated the code, so that it should work with HTTP basic authentication when the credentials are given in the URL of the feed. Maybe you can compile and test the new code for you feed. Otherwise I could provide you the binary package.

**Comment by dasDirksche** [comment]
If you would give me a step by step description what I have to do to compile I would like to try it. Maybe in german?

Am Samstag, 6. Januar 2018 schrieb CarolusMagnus:

**Comment by dasDirksche** [comment]
Otherwise sent mevthe package please.

**Comment by dasDirksche** [comment]
I built a .rpm with SailfishOS SDK. Now the download of the episodes works. But now there is one problem. When I leave the app by swiping right/left the small window on the desktop is complete transparent.file:///home/anjaunddirk/Schreibtisch/Screenshot_20180107_001.png

**Comment by CarolusMagnus** [comment]
I could not reproduce the problem, but I redesigned the Cover page nevertheless. The current version is now submitted to Jolla Harbour.
