### ISSUE TITLE
Refresh podcasts on startup 

### ISSUE THREAD

**Issue by tanghus** [CarolusMagnus/Podcatcher#30]
First: thanks for a great podcast client!

When starting the app it refreshes all the podcasts. As I have quite a lot, it makes the app unresponsive for several minutes.

A switch in settings would fix it for me.

btw: I don't have it set to auto-download.

**Comment by CarolusMagnus** [comment]
Thanks for your feedback! I admit this is a problem. My aim for the future is to rewrite the whole RSS parsing using QXmlStreamReader, which should be much faster. Nevertheless, making the auto-refresh optional is also a good idea, which I will implement in the next time.

**Comment by CarolusMagnus** [comment]
Fixed: new parser and refresh on startup optional.
