### ISSUE TITLE
linuxgamecastweekly is wrongly parsed

### ISSUE THREAD

**Issue by idnovic** [CarolusMagnus/Podcatcher#32]
RSS source
https://linuxgamecast.com/feed/lgcweeklyaudio/

what happens while parsing is:
https://linuxgamecast.com/video/LWDW-20YearsOfSource.mp3

what should happen is:
https://linuxgamecast.com/video/LWDW/LWDW-20YearsOfSource.mp3

Because the rss feed is wrongly parsed the download of media fails.

**Comment by CarolusMagnus** [comment]
I could not find any problems with the parser. It looks like their server wants to have the HTTP User Agent header set, otherwise it refuses to serve the download file. 
I added the user agent to the request and now it seems to work.

**Comment by idnovic** [comment]
thank you, I was writing with the podcaster and that was the explanation from him.
Waiting for the update in openrepos.
Have a nice day

**Comment by krayon** [comment]
@idnovic You may also want to tell them their feed doesn't validate with quite a few issues they should fix:
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Flinuxgamecast.com%2Ffeed%2Flgcweeklyaudio%2F
