### ISSUE TITLE
More contrast color scheme

### ISSUE THREAD

**Issue by qeef** [CarolusMagnus/Podcatcher#36]
My problem is that when Freedom Ambience is in use the difference between new and already played episodes is quite small.

Is it possible to change these colors somehow? Or the problem is only in Freedom Ambience?

Thanks!

**Comment by CarolusMagnus** [comment]
Actually it is not only a problem with the freedom ambiance, but also with a few others. Making a whitish color even more white is not optimal. Changing the color depending on the actual theme color seems a bit complicated. But if you have an idea for an easy change, which would fit for (nearly all) ambiances, just tell me.

**Comment by qeef** [comment]
Not 100% sure but think that the problem is on lines https://github.com/CarolusMagnus/Podcatcher/blob/3b19e3b8ba74dddaada55cd42584b103f7701fa3/sailfish/qml/pages/PodcastEpisodesList.qml#L131 for downloaded not played and https://github.com/CarolusMagnus/Podcatcher/blob/3b19e3b8ba74dddaada55cd42584b103f7701fa3/sailfish/qml/pages/PodcastEpisodesList.qml#L423 for played.

Looking at [Theme cheat sheet](https://sailfishos.org/wp-content/uploads/2016/06/theme_cheatsheet.png) I would suggest to try these two colors combinations:
- *Highlight* for downloaded not played and *Primary* for played.
- *Highlight background* for downloaded not played and *Highlight dimmer* for played.

**Comment by CarolusMagnus** [comment]
Thanks for your effort. I think your first proposal works quite nice.
