### ISSUE TITLE
Long titles overlap url

### ISSUE THREAD

**Issue by trin94** [CarolusMagnus/Podcatcher#39]
Hey,

for long titles the layout is not yet ideal.

Please see attached screenshot.  

#### Device
* Xperia X
* Sailfish version: `2.2.0.29`

Thank you and regards,  
trin94

![screenshot_20180716_001](https://user-images.githubusercontent.com/12988790/42750210-af921072-88e6-11e8-9470-4924a36698eb.png)

**Comment by CarolusMagnus** [comment]
Fixed in today's update.
