### ISSUE TITLE
[Feature Request] Mark episodes as unplayed

### ISSUE THREAD

**Issue by trin94** [CarolusMagnus/Podcatcher#40]
Hey,

I really like the optical hint for played/unplayed episodes.

However I would like to have the option to mark an episode as unplayed:

* in the episode list (by long press - like it is working for *Delete downloaded podacst*)
* in the episode view itself (the one with subscription)

Of course you can do it in a different way.

Thank you and regards
trin94

**Comment by CarolusMagnus** [comment]
Thanks for your comment. I implemented the first option.
