### ISSUE TITLE
See / copy URL for podcast

### ISSUE THREAD

**Issue by sbridger** [CarolusMagnus/Podcatcher#58]
So Lingthusiasm is not refreshing at the moment. There are 3 different sources if I search for it. 
Which one am I using?
How do I share the podcast to someone else.

Nice to have a menu option to see (or edit) URL, copy to clipboard, and maybe share.

It would be useful to be able to get the url of a specific episode to share also.

**Comment by CarolusMagnus** [comment]
That is a good idea!

**Comment by sjn** [comment]
Podcatcher 1.9.13 has this feature. Maybe it's safe to close this ticket? :-)

**Comment by sbridger** [comment]
Thanks.
I would like to test it, but my XA2 lost its cellular modem, and I reflashed it to Android to check it really was dead. Havn't reverted to sfos yet, or gotten a new phone.
