### ISSUE TITLE
Downloaded episodes are not played

### ISSUE THREAD

**Issue by ekari** [CarolusMagnus/Podcatcher#6]
After an episode has been downloaded a play button appears. When tapping the button "Last played" -message with a current timestamp appears under the title, but nothing else happens.

The episode can be found and played via a filebrowser, so the download works ok.

Tested on Jolla 1 with various different feeds.

**Comment by CarolusMagnus** [comment]
Does this happen for all podcasts or just a certain one? Could you please provide me a URL of such a problematic podcast.
If you press the play button the downloaded file should be opened with the default application, i.e. the media player.

**Comment by ekari** [comment]
Ok, I thought that Podcatcher itself would play the episode. Now that I reinstalled the media player by Jolla everything seems ok.
